package testCases;

import org.testng.annotations.Test;

import pageObjects.WPAdmin;
import pageObjects.WPHomePage;
import pageObjects.WPMissingTicket;
import pageObjects.WPSearchResultsPage;
import utility.Log;
import utility.TestSetUp;
import utility.Utils;

/**
 * 
 * @author QA - Rahul Tiwari
 *
 *This Test Case will contains various methods both positive and negative related with Missing Cash back.
 *It will take help of an external Jar known as admin Jar for fetching exit ID
 *Pre-requisite: Amazon Store needs to be present on an environment where scripts will be executed.
 *
 */
public class WP_VerifyMissingCashBackFunctionality extends TestSetUp{

	/**
	 * This Method will verify Missing Cash back scenario in which exit id is generated by searching 
	 * Amazon Store and clicking first Activate Cash back Link. Once exit id is generated, it will raise a ticket successfully
	 * from My Earnings Page.
	 */
	@Test(enabled=true)
	public void raiseATicketSuccessFullyFromMyEarningPage() {
		String started="Validation of Successful Adding a Ticket for Missing Cashback ----- Started";
		String completed="Validation of Successful Adding a Ticket for Missing Cashback ----- Completed";
		Log.info(started);
		reportStep(started, "INFO");
		String email=Utils.generateRandomEmailId();
		String password=Utils.getTestData(1, "password");
		String mobile=Utils.generateRandomMobileNumber();
		String itemToBeSearched=Utils.getTestData(7, "itemToBeSearched");
		String transactionID=Utils.getTestData(7, "transactionID");
		String couponCode=Utils.getTestData(7, "couponCode");
		String totalAmountPaid=Utils.getTestData(7, "amount");
		String transactionDetails=Utils.getTestData(7, "transactionDetails");
		new WPHomePage(driver, logger).
		clickOnlblSignInSignUP().
		clickOnlnkSignIn().
		clickSignUpTab().
		enterFullNameDuringSignUp(Utils.getTestData(1, "fullName")).
		enterEmailIDDuringSignUp(email).
		enterPasswordSignUp(password).
		enterMobileNumberSignUp(mobile).
		clickJoinWithEmailDuringSignUp().
		enterOtpDuringSignUp(mobile).
		clickVerifyOTP().
		verifyPresenceOfMyAccountLabel().
		searchForVoucherOrStore(itemToBeSearched).
		clickOnVoucherCardActivateCashBack();
		Utils.switchToNewlyOpenWindow(driver);
		Utils.explicitWaitForUrlContains(itemToBeSearched);
		Utils.closeCurrentWindow(driver);
		Utils.switchToParentWindow(driver);
		Utils.openNewTab(driver);
		Utils.switchToNewlyOpenWindow(driver);
		String exitClickId=new WPAdmin(driver, logger).
		retrieveExitClick(driver, email);
		Utils.backDatingAnExitId(driver, exitClickId, Utils.getTestData(8, "partnerType"));
		new WPSearchResultsPage(driver, logger).
		clickMyAccountLabel().
		clickMyEarningLink().
		clickRaiseTicketLink().
		clickDateOfTransactionTextBox().
		clickFourDaysBackDate().
		selectFirstRetailerDropDropDownListInMissingCashBackPage().
		clickSelectLink().
		enterTransactionId(transactionID).
		enterCouponCodeUsed(couponCode).
		enterTransactionDetails(transactionDetails).
		enterTotalAmountPaid(totalAmountPaid).
		clickChkBoxTermsAndConditions().
		uploadFile(System.getProperty("user.dir")+"/src/main/resources/missingCashBackFiles/test_less_than_2mb.jpg").
		clickSubmitButton().
		verifyPresenceOfsuccessMessageSubmitTicket();
		Log.info(completed);
		reportStep(completed, "PASS");
	}
	
	/***
	 * Below method will validate uploading a png file less than 2 mb and then submitting ticket
	 */
	@Test(enabled=true)
	public void raiseATicketSuccessFullyViaUploadingAFileLessThanTwoMB() {
		String started="Validation of Successful Adding a Ticket for Missing Cashback ----- Started";
		String completed="Validation of Successful Adding a Ticket for Missing Cashback ----- Completed";
		Log.info(started);
		reportStep(started, "INFO");
		
		String email=Utils.generateRandomEmailId();
		String password=Utils.getTestData(1, "password");
		String mobile=Utils.generateRandomMobileNumber();
		String itemToBeSearched=Utils.getTestData(7, "itemToBeSearched");
		String transactionID=Utils.getTestData(7, "transactionID");
		String couponCode=Utils.getTestData(7, "couponCode");
		String totalAmountPaid=Utils.getTestData(7, "amount");
		String transactionDetails=Utils.getTestData(7, "transactionDetails");
		new WPHomePage(driver, logger).
		clickOnlblSignInSignUP().
		clickOnlnkSignIn().
		clickSignUpTab().
		enterFullNameDuringSignUp(Utils.getTestData(1, "fullName")).
		enterEmailIDDuringSignUp(email).
		enterPasswordSignUp(password).
		enterMobileNumberSignUp(mobile).
		clickJoinWithEmailDuringSignUp().
		enterOtpDuringSignUp(mobile).
		clickVerifyOTP().
		verifyPresenceOfMyAccountLabel().
		searchForVoucherOrStore(itemToBeSearched).
		clickOnVoucherCardActivateCashBack();
		Utils.switchToNewlyOpenWindow(driver);
		Utils.explicitWaitForUrlContains(itemToBeSearched);
		Utils.closeCurrentWindow(driver);
		Utils.switchToParentWindow(driver);
		Utils.openNewTab(driver);
		Utils.switchToNewlyOpenWindow(driver);
		String exitClickId=new WPAdmin(driver, logger).
		retrieveExitClick(driver, email);
		Utils.backDatingAnExitId(driver, exitClickId, Utils.getTestData(8, "partnerType"));
		new WPSearchResultsPage(driver, logger).
		clickMyAccountLabel().
		clickMyEarningLink().
		clickRaiseTicketLink().
		clickDateOfTransactionTextBox().
		clickFourDaysBackDate().
		selectFirstRetailerDropDropDownListInMissingCashBackPage().
		clickSelectLink().
		enterTransactionId(transactionID).
		enterCouponCodeUsed(couponCode).
		enterTransactionDetails(transactionDetails).
		enterTotalAmountPaid(totalAmountPaid).
		uploadFile(System.getProperty("user.dir")+"/src/main/resources/missingCashBackFiles/test_less_than_2mb.png").
		clickChkBoxTermsAndConditions().
		clickSubmitButton().
		verifyPresenceOfsuccessMessageSubmitTicket();
		Log.info(completed);
		reportStep(completed, "PASS");
	}
	
	/**
	 * This Method will verify Missing Cash back scenario in which exit id is generated by searching 
	 * Amazon Store and clicking first Activate Cash back Link. Once exit id is generated, it will raise a ticket successfully
	 * from Missing CashBack Page.
	 * 
	 */
	@Test(enabled=true)
	public void raiseATicketSuccessFullyFromMissingCashBackPage() {
		String started="Validation of Successful Adding a Ticket for Missing Cashback ----- Started";
		String completed="Validation of Successful Adding a Ticket for Missing Cashback ----- Completed";
		Log.info(started);
		reportStep(started, "INFO");
		
		String email=Utils.generateRandomEmailId();
		String password=Utils.getTestData(1, "password");
		String mobile=Utils.generateRandomMobileNumber();
		String itemToBeSearched=Utils.getTestData(7, "itemToBeSearched");
		String transactionID=Utils.getTestData(7, "transactionID");
		String couponCode=Utils.getTestData(7, "couponCode");
		String totalAmountPaid=Utils.getTestData(7, "amount");
		String transactionDetails=Utils.getTestData(7, "transactionDetails");
		new WPHomePage(driver, logger).
		clickOnlblSignInSignUP().
		clickOnlnkSignIn().
		clickSignUpTab().
		enterFullNameDuringSignUp(Utils.getTestData(1, "fullName")).
		enterEmailIDDuringSignUp(email).
		enterPasswordSignUp(password).
		enterMobileNumberSignUp(mobile).
		clickJoinWithEmailDuringSignUp().
		
		
		enterOtpDuringSignUp(mobile).
		clickVerifyOTP().
		verifyPresenceOfMyAccountLabel().
		searchForVoucherOrStore(itemToBeSearched).
		clickOnVoucherCardActivateCashBack();
		Utils.switchToNewlyOpenWindow(driver);
		Utils.explicitWaitForUrlContains(itemToBeSearched);
		Utils.closeCurrentWindow(driver);
		Utils.switchToParentWindow(driver);
		Utils.openNewTab(driver);
		Utils.switchToNewlyOpenWindow(driver);
		String exitClickId=new WPAdmin(driver, logger).
		retrieveExitClick(driver, email);
		Utils.backDatingAnExitId(driver, exitClickId, Utils.getTestData(8, "partnerType"));
		new WPSearchResultsPage(driver, logger).
		clickMyAccountLabel().
		clickMissingCashBackLink().
		clickAddTicketLink().
		clickDateOfTransactionTextBox().
		clickFourDaysBackDate().
		selectFirstRetailerDropDropDownListInMissingCashBackPage().
		clickSelectLink().
		enterTransactionId(transactionID).
		enterCouponCodeUsed(couponCode).
		enterTransactionDetails(transactionDetails).
		enterTotalAmountPaid(totalAmountPaid).
		clickChkBoxTermsAndConditions().
		uploadFile(System.getProperty("user.dir")+"/src/main/resources/missingCashBackFiles/test_less_than_2mb.pdf").
		clickSubmitButton().
		verifyPresenceOfsuccessMessageSubmitTicket();
		Log.info(completed);
		reportStep(completed, "PASS");
	}

	/**
	 * This method will verify status of missing ticket is changed to "Sent To Retailer" and then
	 * status of the same ticket getting changed to Resolved.
	 */
	@Test(enabled=true)
	public void verifyPhasesOfMissingCashBackTicketsForANewUser() {
		String started="Validation of Phases of Tickets for Missing Cashback ----- Started";
		String completed="Validation of Phases of Tickets for Missing Cashback ----- Completed";
		Log.info(started);
		reportStep(started, "INFO");
		
		String email=Utils.generateRandomEmailId();
		String password=Utils.getTestData(1, "password");
		String mobile=Utils.generateRandomMobileNumber();
		String itemToBeSearched=Utils.getTestData(7, "itemToBeSearched");
		String transactionID=Utils.getTestData(7, "transactionID");
		String couponCode=Utils.getTestData(7, "couponCode");
		String totalAmountPaid=Utils.getTestData(7, "amount");
		String transactionDetails=Utils.getTestData(7, "transactionDetails");
		new WPHomePage(driver, logger).
		clickOnlblSignInSignUP().
		clickOnlnkSignIn().
		clickSignUpTab().
		enterFullNameDuringSignUp(Utils.getTestData(1, "fullName")).
		enterEmailIDDuringSignUp(email).
		enterPasswordSignUp(password).
		enterMobileNumberSignUp(mobile).
		clickJoinWithEmailDuringSignUp().
		
		
		enterOtpDuringSignUp(mobile).
		clickVerifyOTP().
		verifyPresenceOfMyAccountLabel().
		searchForVoucherOrStore(itemToBeSearched).
		clickOnVoucherCardActivateCashBack();
		Utils.switchToNewlyOpenWindow(driver);
		Utils.explicitWaitForUrlContains(itemToBeSearched);
		Utils.closeCurrentWindow(driver);
		Utils.switchToParentWindow(driver);
		Utils.openNewTab(driver);
		Utils.switchToNewlyOpenWindow(driver);
		String exitClickId=new WPAdmin(driver, logger).
		retrieveExitClick(driver, email);
		Utils.backDatingAnExitId(driver, exitClickId, Utils.getTestData(8, "partnerType"));
		Utils.switchToParentWindow(driver);
		new WPSearchResultsPage(driver, logger).
		clickMyAccountLabel().
		clickMyEarningLink().
		clickRaiseTicketLink().
		clickDateOfTransactionTextBox().
		clickFourDaysBackDate().
		selectFirstRetailerDropDropDownListInMissingCashBackPage().
		clickSelectLink().
		enterTransactionId(transactionID).
		enterCouponCodeUsed(couponCode).
		enterTransactionDetails(transactionDetails).
		enterTotalAmountPaid(totalAmountPaid).
		clickChkBoxTermsAndConditions().
		clickSubmitButton().
		clickCloseIconInPopUp().
		verifyPresenceOfReceivedStatus();
		Utils.switchToNewlyOpenWindow(driver);
		new WPAdmin(driver, logger).
		changeStatusMissingCashBackTicketToSentToRetailer(driver, exitClickId);
		Utils.switchToParentWindow(driver);
		Utils.refresh(driver);
		new WPMissingTicket(driver, logger).
		verifyPresenceOfSentToRetailerStatus();
		Utils.switchToNewlyOpenWindow(driver);
		new WPAdmin(driver, logger).
		changeStatusMissingCashBackTicketToResolved(driver);
		Utils.switchToParentWindow(driver);
		Utils.refresh(driver);
		new WPMissingTicket(driver, logger).
		verifyPresenceOfResolvedStatus();
		Log.info(completed);
		reportStep(completed, "PASS");
	}

	/**
	 * This method will verify all labels in Missing Cash back Form for a new user.
	 */
	@Test(enabled=true)
	public void verifyDefaultContentOfMissingCashBackForm() {
		String started="Validation of default content of Missing Cashback Form----- Started";
		String completed="Validation of default content of Missing Cashback Form ----- Completed";
		Log.info(started);
		reportStep(started, "INFO");
		
		String email=Utils.generateRandomEmailId();
		String password=Utils.getTestData(1, "password");
		String mobile=Utils.generateRandomMobileNumber();
		String itemToBeSearched=Utils.getTestData(7, "itemToBeSearched");
		new WPHomePage(driver, logger).
		clickOnlblSignInSignUP().
		clickOnlnkSignIn().
		clickSignUpTab().
		enterFullNameDuringSignUp(Utils.getTestData(1, "fullName")).
		enterEmailIDDuringSignUp(email).
		enterPasswordSignUp(password).
		enterMobileNumberSignUp(mobile).
		clickJoinWithEmailDuringSignUp().
		
		
		enterOtpDuringSignUp(mobile).
		clickVerifyOTP().
		verifyPresenceOfMyAccountLabel().
		searchForVoucherOrStore(itemToBeSearched).
		clickOnVoucherCardActivateCashBack();
		Utils.switchToNewlyOpenWindow(driver);
		Utils.explicitWaitForUrlContains(itemToBeSearched);
		Utils.closeCurrentWindow(driver);
		Utils.switchToParentWindow(driver);
		new WPSearchResultsPage(driver, logger).
		clickMyAccountLabel().
		clickMyEarningLink().
		clickRaiseTicketLink().
		verifyDateOfTransactionLabelIsVisible().
		verifyEnterDateOfTransactionLabelIsVisible().
		verifyRetailerYouShoppedAtLabelIsVisible().
		verifySelectExitClickAndTransactionDetailsLabelIsVisible().
		verifylblHaveMultipleClickSameRetailersLabelIsVisible().
		verifyExitClickTimeTableColumnIsVisible().
		verifyTransactionIdTableColumnIsVisible().
		verifyTransactionAmountTableListIsVisible().
		verifyEarningsTableListIsVisible().
		verifyCouponDetailsTableListIsVisible().
		verifyStatusTableListIsVisible().
		verifyEnterMissingCashbackDetailsLabelIsVisible().
		verifyYourTransactionIDIsVisible().
		verifyTotalAmountPaidLabelIsVisible().
		verifyCouponCodeUsedIsVisible().
		verifyDetailsOfTransactionLabelIsVisible();
		Log.info(completed);
		reportStep(completed, "PASS");
	}
	
	/**
	 * This method will validate error message if user is trying to 
	 * raise ticket for a date for which no exit clik id is generated.
	 */
	@Test(enabled=true)
	public void verifyErrorMessageWhileRaisingTicketIfNoExitIdGenerated() {
		String started="Validation of Error Message: \"Sorry, we don’t see any clicks from your account on this date. Please select a valid date of transaction or you can reach us\"   in Missing Cashback Form----- Started";
		String completed="Validation of Error Message: \"Sorry, we don’t see any clicks from your account on this date. Please select a valid date of transaction or you can reach us\"   in Missing Cashback Form------ Completed";
		Log.info(started);
		reportStep(started, "INFO");
		
		String email=Utils.generateRandomEmailId();
		String password=Utils.getTestData(1, "password");
		String mobile=Utils.generateRandomMobileNumber();
		new WPHomePage(driver, logger).
		clickOnlblSignInSignUP().
		clickOnlnkSignIn().
		clickSignUpTab().
		enterFullNameDuringSignUp(Utils.getTestData(1, "fullName")).
		enterEmailIDDuringSignUp(email).
		enterPasswordSignUp(password).
		enterMobileNumberSignUp(mobile).
		clickJoinWithEmailDuringSignUp().
		
		
		enterOtpDuringSignUp(mobile).
		clickVerifyOTP().
		verifyPresenceOfMyAccountLabel().
		clickMyAccountLabel().
		clickMyEarningLink().
		clickRaiseTicketLink().
		clickDateOfTransactionTextBox().
		clickTodaysDateInDatePicker().
		verifySorryWeDontSeeAnyClickErrorMsgIsVisible();
		Log.info(completed);
		reportStep(completed, "PASS");
	}
	
	/**
	 * This method will validate value of Date, Retailer Name, Transaction Amount, etc of a ticket raised
	 * in Missing CashBack Page.
	 */
	@Test(enabled=true)
	public void validateValuesOfDateRetailerNameTransactionAmountInMissingCashbackPage() {
		String started="Validation of Successful Adding a Ticket for Missing Cashback ----- Started";
		String completed="Validation of Successful Adding a Ticket for Missing Cashback ----- Completed";
		Log.info(started);
		reportStep(started, "INFO");
		
		String email=Utils.generateRandomEmailId();
		String password=Utils.getTestData(1, "password");
		String mobile=Utils.generateRandomMobileNumber();
		String itemToBeSearched=Utils.getTestData(7, "itemToBeSearched");
		String transactionID=Utils.getTestData(7, "transactionID");
		String couponCode=Utils.getTestData(7, "couponCode");
		String totalAmountPaid=Utils.getTestData(7, "amount");
		String transactionDetails=Utils.getTestData(7, "transactionDetails");
		new WPHomePage(driver, logger).
		clickOnlblSignInSignUP().
		clickOnlnkSignIn().
		clickSignUpTab().
		enterFullNameDuringSignUp(Utils.getTestData(1, "fullName")).
		enterEmailIDDuringSignUp(email).
		enterPasswordSignUp(password).
		enterMobileNumberSignUp(mobile).
		clickJoinWithEmailDuringSignUp().
		
		
		enterOtpDuringSignUp(mobile).
		clickVerifyOTP().
		verifyPresenceOfMyAccountLabel().
		searchForVoucherOrStore(itemToBeSearched).
		clickOnVoucherCardActivateCashBack();
		Utils.switchToNewlyOpenWindow(driver);
		Utils.explicitWaitForUrlContains(itemToBeSearched);
		Utils.closeCurrentWindow(driver);
		Utils.switchToParentWindow(driver);
		Utils.openNewTab(driver);
		Utils.switchToNewlyOpenWindow(driver);
		String exitClickId=new WPAdmin(driver, logger).
		retrieveExitClick(driver, email);
		Utils.backDatingAnExitId(driver, exitClickId, Utils.getTestData(8, "partnerType"));
		new WPSearchResultsPage(driver, logger).
		clickMyAccountLabel().
		clickMyEarningLink().
		clickRaiseTicketLink().
		clickDateOfTransactionTextBox().
		clickFourDaysBackDate().
		selectFirstRetailerDropDropDownListInMissingCashBackPage().
		clickSelectLink().
		enterTransactionId(transactionID).
		enterCouponCodeUsed(couponCode).
		enterTransactionDetails(transactionDetails).
		enterTotalAmountPaid(totalAmountPaid).
		clickChkBoxTermsAndConditions().
		uploadFile(System.getProperty("user.dir")+"/src/main/resources/missingCashBackFiles/testLessThan2MB.jpeg").
		clickSubmitButton().
		clickCloseIconInPopUp().
		verifyValueOfDate(Utils.todaysDateDdMmmYyyy()).
		verifyNameOfRetailer(Utils.getTestData(7, "retailerName")).
		verifyTransactionAmountValue(totalAmountPaid);
		Log.info(completed);
		reportStep(completed, "PASS");
	}
	
	/**
	 * This method will validate View Ticket Summary functionality and User will send a query
	 * in Missing CashBack Page.
	 */
	@Test(enabled=true)
	public void validateViewTicketFunctionalityInbMissingCashbackPage() {
		String started="Validation of Successful View Ticket Functionality ----- Started";
		String completed="Validation of Successful View Ticket Functionality ----- Completed";
		Log.info(started);
		reportStep(started, "INFO");
		
		String email=Utils.generateRandomEmailId();
		String password=Utils.getTestData(1, "password");
		String mobile=Utils.generateRandomMobileNumber();
		String itemToBeSearched=Utils.getTestData(7, "itemToBeSearched");
		String transactionID=Utils.getTestData(7, "transactionID");
		String couponCode=Utils.getTestData(7, "couponCode");
		String totalAmountPaid=Utils.getTestData(7, "amount");
		String transactionDetails=Utils.getTestData(7, "transactionDetails");
		new WPHomePage(driver, logger).
		clickOnlblSignInSignUP().
		clickOnlnkSignIn().
		clickSignUpTab().
		enterFullNameDuringSignUp(Utils.getTestData(1, "fullName")).
		enterEmailIDDuringSignUp(email).
		enterPasswordSignUp(password).
		enterMobileNumberSignUp(mobile).
		clickJoinWithEmailDuringSignUp().
		enterOtpDuringSignUp(mobile).
		clickVerifyOTP().
		verifyPresenceOfMyAccountLabel().
		searchForVoucherOrStore(itemToBeSearched).
		clickOnVoucherCardActivateCashBack();
		Utils.switchToNewlyOpenWindow(driver);
		Utils.explicitWaitForUrlContains(itemToBeSearched);
		Utils.closeCurrentWindow(driver);
		Utils.switchToParentWindow(driver);
		Utils.openNewTab(driver);
		Utils.switchToNewlyOpenWindow(driver);
		String exitClickId=new WPAdmin(driver, logger).
		retrieveExitClick(driver, email);
		Utils.backDatingAnExitId(driver, exitClickId, Utils.getTestData(8, "partnerType"));
		new WPSearchResultsPage(driver, logger).
		clickMyAccountLabel().
		clickMyEarningLink().
		clickRaiseTicketLink().
		clickDateOfTransactionTextBox().
		clickFourDaysBackDate().
		selectFirstRetailerDropDropDownListInMissingCashBackPage().
		clickSelectLink().
		enterTransactionId(transactionID).
		enterCouponCodeUsed(couponCode).
		enterTransactionDetails(transactionDetails).
		enterTotalAmountPaid(totalAmountPaid).
		clickChkBoxTermsAndConditions().
		clickSubmitButton().
		clickCloseIconInPopUp().
		clickViewTicketLink().
		enterInReplyTextArea().
		clickSubmitButtonForReply().
		verifyPresenceOfinfoMessageQuerySubmittedSuccessFully().
		clickCloseIconInPopUp();
		Log.info(completed);
		reportStep(completed, "PASS");
	}
	
	/**
	 * This method will validate raising ticket when multiple exit click ID is present.
	 */
	@Test(enabled=true)
	public void validateRaisingTicketMultipleExitId() {
		String started="Validation of Successful Multiple Exit ID Functionality ----- Started";
		String completed="Validation of Successful Multiple Exit ID Functionality ----- Completed";
		Log.info(started);
		reportStep(started, "INFO");
		String email=Utils.generateRandomEmailId();
		String password=Utils.getTestData(1, "password");
		String mobile=Utils.generateRandomMobileNumber();
		String itemToBeSearched=Utils.getTestData(7, "itemToBeSearched");
		String itemToBeSearched1=Utils.getTestData(7, "itemToBeSearched1");
		String itemToBeSearched2=Utils.getTestData(7, "itemToBeSearched2");
		String transactionID=Utils.getTestData(7, "transactionID");
		String couponCode=Utils.getTestData(7, "couponCode");
		String totalAmountPaid=Utils.getTestData(7, "amount");
		String transactionDetails=Utils.getTestData(7, "transactionDetails");
		new WPHomePage(driver, logger).
		clickOnlblSignInSignUP().
		clickOnlnkSignIn().
		clickSignUpTab().
		enterFullNameDuringSignUp(Utils.getTestData(1, "fullName")).
		enterEmailIDDuringSignUp(email).
		enterPasswordSignUp(password).
		enterMobileNumberSignUp(mobile).
		clickJoinWithEmailDuringSignUp().
		enterOtpDuringSignUp(mobile).
		clickVerifyOTP().
		verifyPresenceOfMyAccountLabel().
		searchForVoucherOrStore(itemToBeSearched).
		clickOnVoucherCardActivateCashBack();
		Utils.switchToNewlyOpenWindow(driver);
		Utils.explicitWaitForUrlContains(itemToBeSearched);
		Utils.closeCurrentWindow(driver);
		Utils.switchToParentWindow(driver);
		Utils.openNewTab(driver);
		Utils.switchToNewlyOpenWindow(driver);
		String exitClickId=new WPAdmin(driver, logger).
		retrieveExitClick(driver, email);
		Utils.backDatingAnExitId(driver, exitClickId, Utils.getTestData(8, "partnerType"));
		new WPSearchResultsPage(driver, logger).
		searchForVoucherOrStore(itemToBeSearched1).
		clickOnVoucherCardActivateCashBack();
		Utils.switchToNewlyOpenWindow(driver);
		Utils.explicitWaitForUrlContains(itemToBeSearched1);
		Utils.closeCurrentWindow(driver);
		Utils.switchToParentWindow(driver);
		Utils.switchToNewlyOpenWindow(driver);
		exitClickId=new WPAdmin(driver, logger).
		retrieveMostRecentExitClick(driver);
		Utils.backDatingAnExitId(driver, exitClickId, Utils.getTestData(8, "partnerType"));
		new WPSearchResultsPage(driver, logger).
		searchForVoucherOrStore(itemToBeSearched2).
		clickOnVoucherCardActivateCashBack();
		Utils.switchToNewlyOpenWindow(driver);
		Utils.explicitWaitForUrlContains(itemToBeSearched2);
		Utils.closeCurrentWindow(driver);
		Utils.switchToParentWindow(driver);
		Utils.switchToNewlyOpenWindow(driver);
		exitClickId=new WPAdmin(driver, logger).
		retrieveMostRecentExitClick(driver);
		Utils.backDatingAnExitId(driver, exitClickId, Utils.getTestData(8, "partnerType"));
		new WPSearchResultsPage(driver, logger).
		clickMyAccountLabel().
		clickMyEarningLink().
		clickRaiseTicketLink().
		clickDateOfTransactionTextBox().
		clickFourDaysBackDate().
		selectFirstRetailerDropDropDownListInMissingCashBackPage().
		clickSelectLink().
		enterTransactionId(transactionID).
		enterCouponCodeUsed(couponCode).
		enterTransactionDetails(transactionDetails).
		enterTotalAmountPaid(totalAmountPaid).
		clickChkBoxTermsAndConditions().
		clickSubmitButton().
		verifyPresenceOfinfoMessageQuerySubmittedSuccessFully().
		clickCloseIconInPopUp();
		Log.info(completed);
		reportStep(completed, "INFO");
	}
	
	/**
	 * This method will validate error if Size of a file is more than 2 MB while raising ticket.
	 * Also this will verify error message in case User is not clicking Terms and Condition Check Box
	 */
	@Test(enabled=true)
	public void validateErrorIfSizeIsMoreThanTwoMB() {
		String started="Validation of Errors If Size of a File is More than Two MB Functionality ----- Started";
		String completed="Validation of Errors If Size of a File is More than Two MB Functionality----- Completed";
		Log.info(started);
		reportStep(started, "INFO");
		
		String email=Utils.generateRandomEmailId();
		String password=Utils.getTestData(1, "password");
		String mobile=Utils.generateRandomMobileNumber();
		String itemToBeSearched=Utils.getTestData(7, "itemToBeSearched");
		String transactionID=Utils.getTestData(7, "transactionID");
		String couponCode=Utils.getTestData(7, "couponCode");
		String totalAmountPaid=Utils.getTestData(7, "amount");
		String transactionDetails=Utils.getTestData(7, "transactionDetails");
		new WPHomePage(driver, logger).
		clickOnlblSignInSignUP().
		clickOnlnkSignIn().
		clickSignUpTab().
		enterFullNameDuringSignUp(Utils.getTestData(1, "fullName")).
		enterEmailIDDuringSignUp(email).
		enterPasswordSignUp(password).
		enterMobileNumberSignUp(mobile).
		clickJoinWithEmailDuringSignUp().
		enterOtpDuringSignUp(mobile).
		clickVerifyOTP().
		verifyPresenceOfMyAccountLabel().
		searchForVoucherOrStore(itemToBeSearched).
		clickOnVoucherCardActivateCashBack();
		Utils.switchToNewlyOpenWindow(driver);
		Utils.explicitWaitForUrlContains(itemToBeSearched);
		Utils.closeCurrentWindow(driver);
		Utils.switchToParentWindow(driver);
		Utils.openNewTab(driver);
		Utils.switchToNewlyOpenWindow(driver);
		String exitClickId=new WPAdmin(driver, logger).
		retrieveExitClick(driver, email);
		Utils.backDatingAnExitId(driver, exitClickId, Utils.getTestData(8, "partnerType"));
		new WPSearchResultsPage(driver, logger).
		clickMyAccountLabel().
		clickMyEarningLink().
		clickRaiseTicketLink().
		clickDateOfTransactionTextBox().
		clickFourDaysBackDate().
		selectFirstRetailerDropDropDownListInMissingCashBackPage().
		clickSelectLink().
		enterTransactionId(transactionID).
		enterCouponCodeUsed(couponCode).
		enterTransactionDetails(transactionDetails).
		enterTotalAmountPaid(totalAmountPaid).
		uploadFile(System.getProperty("user.dir")+"/src/main/resources/missingCashBackFiles/test_more_than_2mb.jpeg").
		clickChkBoxTermsAndConditions().
		clickSubmitButton().
		verifyErrorInUploadIsVisible().
		uploadFile(System.getProperty("user.dir")+"/src/main/resources/missingCashBackFiles/test_less_than_2mb.png").
		uploadFile(System.getProperty("user.dir")+"/src/main/resources/missingCashBackFiles/test_more_than_2mb.jpg").
		clickSubmitButton().
		verifyErrorInUploadIsVisible().
		uploadFile(System.getProperty("user.dir")+"/src/main/resources/missingCashBackFiles/test_less_than_2mb.png").
		uploadFile(System.getProperty("user.dir")+"/src/main/resources/missingCashBackFiles/test_more_than_2mb.pdf").
		clickSubmitButton().
		verifyErrorInUploadIsVisible().
		uploadFile(System.getProperty("user.dir")+"/src/main/resources/missingCashBackFiles/test_less_than_2mb.png").
		uploadFile(System.getProperty("user.dir")+"/src/main/resources/missingCashBackFiles/test_More_than_2mb.png").
		clickSubmitButton().
		verifyErrorInUploadIsVisible().
		uploadFile(System.getProperty("user.dir")+"/src/main/resources/missingCashBackFiles/test_less_than_2mb.png").
		clickChkBoxTermsAndConditions().
		clickSubmitButton().
		verifyPleaseAcceptTermsErrorMsgIsVisible();
		Log.info(completed);
		reportStep(completed, "INFO");
	}
}
